from typing import Any

class Tagger:
    def __init__(self, args: str | None = None) -> None: ...
    def parse(self, text: str) -> str: ...
    def parseToNodeList(self, text: str) -> Any: ...
    def __call__(self, text: str) -> Any: ...
